config/routes.rb
Rails.application.routes.draw do
	## PUBLIC ##	
 	constraints(:subdomain => /^(?!api)(\w+)/) do 
		resources :users
		
	 	devise_for :users
	 	as :user do
	 		delete "logout" => "devise/sessions#destroy"
	 	end

		match '/auth/:provider/callback', to: 'authentications#create', via: [:get, :post]
		match 'auth/failure', to: redirect('/'), via: [:get, :post]

		match 'welcome', to: 'pages#welcome', as: 'welcome', via: [:get]
		match 'queue', to: 'pages#queue', via: [:get]
		match 'queue/clear', to: 'pages#queue', via: [:get], clear: true
	end

	## API ##
	namespace :api, path: '/', constraints: { subdomain: 'api' }, 
 							   default: { format: 'json' } do
 		get '/' => '/pages#api', as: 'api_root'

 		namespace :v1, path: '/' do
	 		resources :user do
	 			member do
	 				get :friends
	 			end

	 			collection do
	  				get :find_token
					post :oauth_create
	  			end
	 		end
	 	end
 	end

	root to: 'pages#home'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  has_many :authentications, :dependent => :delete_all
  has_and_belongs_to_many(:friends,
                          class_name: 'User',
                          join_table: 'friendship_connections',
                          foreign_key: "user_a_id",
                          association_foreign_key: "user_b_id")

  def self.find_by_token(token)
    User.where(oauth_token: token).first
  end

  def self.data_from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
     user.provider = auth.provider
     user.uid = auth.uid
     user.name = auth.info.name
     user.oauth_token = auth.credentials.token
     user.oauth_expires_at = Time.at(auth.credentials.expires_at)
     user.save!
   end
  end

  def apply_omniauth(auth)
    # In previous omniauth, 'user_info' was used in place of 'raw_info'
    self.email = auth['extra']['raw_info']['email']
    # Again, saving token is optional. If you haven't created the column in authentications table, this will fail
    authentications << Authentication.new(:user_id => self.id, :provider => auth['provider'], :uid => auth['uid'], :token => auth['credentials']['token'])
  
    authentication = authentications.first

    self.provider = authentication.provider
    self.uid = authentication.uid
    self.oauth_token = authentication.token
  end

  def load_friends
      p 'LOADING FRIENDS'
      connections = self.graph.get_connections("me", "friends")

      self.update_attribute(:password, 'asskon123')
      self.save

      connections.each do |connection|
        user_for_uuid = User.where(uid: connection['id']).first

        unless user_for_uuid.nil?
          self.friends << user_for_uuid
          user_for_uuid.friends << self

          self.save(:validate => false)
          user_for_uuid.save(:validate => false)
        end
      end
  end

  def load_name
    self.update_attribute(:name, graph.get_object("me")["name"])
  end

  def graph
    Koala::Facebook::API.new(self.oauth_token)
  end

  def firebase
    Firebase::Client.new "https://friendroulette.firebaseio.com/"
  end

  def matchmake
    self.firebase.set("#{self.uid}", 'null')
    found = false

    current_users = $redis.sort('matchmaking-users')

    current_users.each do |id|
      user = User.where(uid: id).first

      if user.id == self.id
        next
      end

      if user.nil?
        $redis.lrem('matchmaking-users', 0, id)
        next
      end

      if self.friends.include? user
        random_token = SecureRandom.urlsafe_base64(10)

        self.firebase.set("#{self.uid}", random_token)
        user.firebase.set("#{user.uid}", random_token)

        $redis.lrem('matchmaking-users', 0, user.uid)

        found = true
        break
      end
    end

    if !found
      $redis.rpush('matchmaking-users', self.uid)
    end 
  end
end

app/controllers/api/v1/callback_controller.rb
module Api
	module V1
		class CallbackController < ApplicationController
			def facebook
				@user = User.find_for_oauth(env["omniauth.auth"], current_user)
				
				if @user.persisted?
					sign_in_and_redirect @user, :event => :authentication
					set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
				else
					session["devise.facebook_data"] = env["omniauth.auth"]
					redirect_to new_user_registration_url
				end
			end
		end
	end
end

app/controllers/api/v1/firebase_controller.rb
module Api
	module V1
		class FirebaseController < ApplicationController
			skip_before_filter  :verify_authenticity_token
			
			def get_firebase
				user = User.find(params[:id])
			end
		end
	end
end

app/controllers/api/v1/user_controller.rb
module Api
	module V1
		require 'securerandom'
		
		class UserController < ApplicationController
			skip_before_filter  :verify_authenticity_token
			
			def index
				@user = User.all

				render json: @user
			end

			def show
				@user = User.find(params[:id])

				render json: @user
			end

			def find_token
				token = params[:token]

				user = User.find_by_token(token)

				if !user.nil?
					render json: user
				else
					render json: { status: false }
				end
			end

			def friends
				user = User.find(params[:id])

				render json: user.friends
			end

			def oauth_create
				auth = params['oauth']

				existing = User.find_by_token(auth)

				if !existing.nil?
					existing.matchmake

					render json: existing
				else
					graph = Koala::Facebook::API.new(auth)
					profile = graph.get_object("me")

				    id = profile["id"]
				    name = profile["name"]
				    email = profile["email"]

				    user = User.new(uid: id, name: name, email: email, oauth_token: auth, password: 'asskon123asskon123')

				    if user.save
				    	user.load_friends
				    	user.load_name
				    	user.matchmake

				    	render json: user
				    else
				    	render json: user.errors.full_messages
				    end
				end
			end


			def update
				@user = User.find(params[:id])

				@user.update_attributes(user_params)

				render json: { status: true }
			end

			def destroy
				@user = User.find(params[:id])

				@user.destroy

				render json: { status: true }
			end

			private
			def user_params
				params.permit(:name, :uid, :email, :oauth_token, :provider)
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
	def create
		auth = request.env["omniauth.auth"]

	    # Try to find authentication first
	    authentication = Authentication.find_by_provider_and_uid(auth['provider'], auth['uid'])

		if authentication
		    # Authentication found, sign the user in.
		    flash[:notice] = "Signed in successfully."
		    sign_in_and_redirect(:user, authentication.user)
	    else
		    # Authentication not found, thus a new user.
		    user = User.new
		    user.apply_omniauth(auth)
		    user.load_friends
		    user.load_name

		    if user.save(:validate => false)
		    	flash[:notice] = "Account created and signed in successfully."
		    	sign_in_and_redirect(:user, user)
		    else
		    	flash[:error] = "Error while creating a user account. Please try again."
		    	redirect_to root_url
		    end
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:home, :api, :queue]

  def home
  end

  def api
  end

  def welcome
  	render layout: false
  end

  def queue
    if(params[:clear])
      $redis.flushDB
      $redis.set('matchmaking-users', [])
    end

  	ids = $redis.sort('matchmaking-users')
  	@users = []

  	ids.each do |id|
  		user = User.where(uid: id).first
      unless user.nil?  
  	   	@users << user
      end
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @friends = User.find(params[:id]).graph.get_connections("me", "friends")
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_appheader.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>

            <div class="navbar-brand">
                <%= link_to "<i class='fa fa-play-circle'></i>  <span class='light'>Friend</span> Roulette".html_safe, root_path %>
            </div>
        </div>

        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li class="hidden">
                </li>
                <li class="page-scroll">
                    <%= link_to "Users", users_path %>
                </li>
                <li class="page-scroll">
                    <%= link_to "Profile", current_user %>
                </li>

                <li class="page-scroll">
                </li>
                <li class="page-scroll">
                    <% if current_user %>
                        <%= link_to "Logout", logout_path, method: 'delete', id: "sign_out" %>
                    <% else %>
                        <%= link_to "Login", "/auth/facebook", id: "sign_in" %>
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/application/_footer.html.erb
 <footer>   
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline">
                    <li><a href="#page-top">Home</a></li>

                    <li class="footer-menu-divider">&sdot;</li>

                    <li><a href="#about">About</a></li>

                    <li class="footer-menu-divider">&sdot;</li>

                    <li><a href="#download">Download</a></li>

                    <li class="footer-menu-divider">&sdot;</li>

                    <li><a href="#contact">Contact</a></li>
                </ul>
                <p class="copyright text-muted small">Copyright &copy; FriendRoulette 2013. All Rights Reserved</p>
            </div>
        </div>
    </div>
</footer>

app/views/application/_header.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="#page-top">
                <i class="fa fa-play-circle"></i>  <span class="light">Friend</span> Roulette
            </a>
        </div>

        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="#about">About</a>
                </li>
                <li class="page-scroll">
                    <a href="#download">Download</a>
                </li>
                <li class="page-scroll">
                    <a href="#contact">Contact</a>
                </li>

                    <% if current_user %>
                                    <li class="page-scroll">
                        <%= link_to "Profile", current_user %>
                    </li>
                                    <li class="page-scroll">
                        <%= link_to "Logout", logout_path, method: 'delete', id: "sign_out" %>
                    </li>
                    <% else %>
                                    <li class="page-scroll">
                        <%= link_to "Login", "/auth/facebook", id: "sign_in" %>
                                        </li>
                    <% end %>

            </ul>
        </div>
    </div>
</nav>

app/views/application/_javascripts.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js' %>

<%= javascript_include_tag 'http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js' %>

<%= javascript_include_tag 'http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js' %>

app/views/application/_meta.html.erb
<%= csrf_meta_tags %>

app/views/application/_stylesheets.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

<%= stylesheet_link_tag 'http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css' %>

<%= stylesheet_link_tag 'http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css' %>
 
<%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' %>
 
<%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Montserrat:400,700' %>

<%= favicon_link_tag 'favicon.ico' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FriendRoulette</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-custom">
	<head>
	  <title>FriendRoulette</title>
	  <%= render partial: 'stylesheets' %>
	  <%= render partial: 'meta' %>
	</head>
	<body>


		<%= yield %>


		<%= render partial: 'javascripts' %>
	</body>
</html>

app/views/pages/api.html.erb
<h1>API</h1>

app/views/pages/home.html.erb
<%= render partial: 'header' %>
<section class="intro">
        <div class="intro-body">
            <div class="background-shade">
                <h1 class="brand-heading">
                    <span class="light">Friend</span> Roulette
                </h1>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        
                        <p class="intro-text">Make new friends and reconnect with old ones. </p>
                        <div class="page-scroll">
                            <a href="#about" class="btn btn-circle">
                                <i class="fa fa-angle-double-down animated"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="about" class="container content-section text-center">
        <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">About FriendRoulette</h2>
                    <p class="lead">Make new friends and reconnect with old ones. We all have Facebook friends who we rarely talk to but would like to get to know. FriendRoulette lets us do just that.</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <%= image_tag 'photo.jpg', class: 'img-responsive' %>
                </div>
            </div>
    </section>

    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-5 col-sm-6" align="center"> 
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>

                    <h2>Download FriendRoulette</h2>
                    <p>You can download FriendRoulette for FREE on the Apple App Store or the Google Play store.</p>
                    <%= link_to 'Play Store', '#', class: 'btn btn-default btn-lg' %>
                    <%= link_to 'App Store', '#', class: 'btn btn-default btn-lg' %>
                </div>

                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <%= image_tag 'bag.jpg', class: 'img-responsive' %>
                </div>
            </div>
        </div>
    </section>

    <section id="contact" class="banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2>Connect with Us</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <%= link_to '#', class: 'btn btn-default btn-lg' do %>
                                <i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span>
                            <% end %>
                        </li>
                        <li>
                            <%= link_to '#', class: 'btn btn-default btn-lg' do %>
                                <i class="fa fa-github fa-fw"></i> <span class="network-name">GitHub</span>
                            <% end %>
                        </li>
                        <li>
                            <%= link_to '#', class: 'btn btn-default btn-lg' do %>
                                <i class="fa fa-linkedin fa-fw"></i> <span class="network-name">LinkedIn</span>
                            <% end %>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
<%= render partial: 'footer' %>

app/views/pages/queue.html.erb
<h1>Queue</h1>

<ul>
	<% @users.each do |user| %>
		<li><%= user.name %></li>
	<% end %>
</ul>

app/views/pages/welcome.html.erb
<h1>Welcome</h1>

app/views/users/show.html.erb
<%= render partial: 'appheader' %>
<section class="intro">
    <div class="intro-body">
    	<div class="background-shade">
			<h1><%= @user.name %></h1>	
			<p><%= @user.friends.count %> Active Friends</p>
			<p><%= @friends.count %> Friends</p>	
		</div>
	</div>
</section>